language: c
script: dpkg-buildpackage -b -us -uc

install:
   # Package dependencies.
   - sudo apt-get install devscripts equivs
   - sudo mk-build-deps -ir

# whitelist
branches:
   only:
      - master
